[connections.supabase]
SUPABASE_URL = "https://yehrxiatzfrgzitmybnd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaHJ4aWF0emZyZ3ppdG15Ym5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzk4MjMsImV4cCI6MjA2NDk1NTgyM30.0rcJOB_ZZIslH5_3IZxB0Wp9Ct5D0BOJB2j9K6-mEzI"

GOOGLE_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "lively-wave-463209-a3",
  "private_key_id": "ab22bbc95390fe694d97f38bab5082e1d008180f",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC4YiIPDTehZTz7\\n...==\\n-----END PRIVATE KEY-----\\n",
  "client_email": "sheets-access@lively-wave-463209-a3.iam.gserviceaccount.com",
  "client_id": "102172030619797802051",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access%40lively-wave-463209-a3.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

