[connections.supabase]
SUPABASE_URL = "https://yehrxiatzfrgzitmybnd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaHJ4aWF0emZyZ3ppdG15Ym5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzk4MjMsImV4cCI6MjA2NDk1NTgyM30.0rcJOB_ZZIslH5_3IZxB0Wp9Ct5D0BOJB2j9K6-mEzI"
